language: c
compiler:
    - gcc
script: make 
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/ec51097009f538278ab8
        on_success: change
        on_failure: always

